In [9]:
import numpy as np
#ndarray 연산 : 1차원 ndarrary 객체의 연산
a = np.arange(1,4)
b = np.arange(2,5)
print(a)
print(b,'\n')

print(a+b)
print(a*b)
print(a%b)

#기본적으로 1차원 ndarray 객체는 같은 위치의 원소끼리의 
#연산이다. 
#★리스트의 연산은 기본적으로 문자열의 연산과 같다고 생각하면 된다.

print('\n',a+3)

[1 2 3]
[2 3 4] 

[3 5 7]
[ 2  6 12]
[1 2 3]

 [4 5 6]


In [19]:
#list의 ndarray 변환의 유용성: 주식 일간 고가,저가 비교
high = [92700,92400,92100,94300,92300]
low = [90000,91100,91700,92100,90900]

arr_high = np.array(high)
arr_low = np.array(low)

arr_diff = arr_high - arr_low
print(arr_diff)

#list와는 다르게 원소간 연산이 필요한 경우 쉽게 할 수 있다.
#ex)주가 지수 출력: 구성-> 고가 3배, 저가 2배 후 합 구성
hp = arr_high * 3
lp = arr_low * 2
st_index = hp + lp
print(st_index)

#만일 고가, 저가가 2차원 리스트 형태로 같이 주어진다면?
data = [[92700,92400,92100,94300,92300], 
        [90000,91100,91700,92100,90900]
]

ar_data = np.array(data)
print(ar_data)
print(ar_data[0]*3+ar_data[1]*2)


[2700 1300  400 2200 1400]
[458100 459400 459700 467100 458700]
[[92700 92400 92100 94300 92300]
 [90000 91100 91700 92100 90900]]
[458100 459400 459700 467100 458700]
