In [3]:
#ndarry 객체
#리스트,튜플, 딕셔너리 같이 numpy에서 정의된 데이터 타입
#array()함수로 ndarry객체 전환
import numpy as np

data1 = [1,2,3,4]

arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
#2차원 리스트의 ndarry 변환
data2 = [
    [1,2],
    [3,4]
]
arr2 = np.array(data2)
print(arr2)
# 컴마 없이 표현되어 행렬을 만들었다.

print(type(arr2))
print(type(arr2[0]))
#2차원 리스트의 전환에 내부 리스트 또한 
#ndarry 객체로 전환됨을 확인할 수 있다.


[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
#ndarry의 정보 조회
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

#.shape: (행,열)의 모양 조회
#.ndim: 데이터의 차원(가로,세로축이 있는 2차원 데이터)
#.dtype: ndarry에 저장된 데이터가 32비트 표현 가능한 정수

(2, 2)
2
int32


In [12]:
#zeros(),ones()함수
print(np.zeros(3))
print(np.zeros((3,3)))
print(np.ones(3))
print(np.ones([3,3]))

#해당 함수에 스칼라 값을 넣어서 0이나 1배열을 만들거나
#리스트, 튜플 값을 넣어서 행렬의 형식으로 표현 가능하다.

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
#arange함수: 지정된 범위 내의 규칙적 숫자를 갖는 ndarry 객체 출력
print(np.arange(5))
print(np.arange(1,5))
print(np.arange(1,5,2))

#arrange(a,b,c)
#a에서 시작해서 b-1까지 C씩 증가하는 ndarry 객체 변환
#디폴트 값: a=0,c=1

[0 1 2 3 4]
[1 2 3 4]
[1 3]


In [4]:
#.reshape(): 내부 데이터 변경 없이 배열 변경
ndarr1 = np.arange(6)
ndarr2 = ndarr1.reshape(2,3)
print(ndarr2)

#.reshape(행,열): 해당 행과 열을 가진 행렬로 데이터 배열 변경

[[0 1 2]
 [3 4 5]]
