In [3]:
#numpy: 연산을 위한 파이썬 패키지, ndarrary 객체 사용.
#다차원 배열 및 행렬 지원

import numpy as np
data = [1,2,3]
arr = np.array(data)
print(arr)
print(type(arr))
# ndarry 객체 사용-> 리스트와 비슷
# 특징: array 함수로 ndarry 객체 반환, 모습은 비슷하지만
#종류는 별도로 지정되어 있다.

[1 2 3]
<class 'numpy.ndarray'>


In [14]:
#파이썬 리스트 활용 연산
data = [1,2,3]

result = []
for i in data:
    result.append(i*10)
print(result)

#numpy를 활용한 동일 연산
import numpy as np
arr = np.array([1,2,3])
result = 10*arr
print(result)
##여기서 arr, result는 리스트가 아닌 객체이기에 10*가 10번 
##반복이 아니라 개별 원소에 10을 곱해준 형태가 된다.

#인덱싱을 활용한 1행 출력
data2d=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

print(data2d[0])
#이 경우 행의 출력은 간단하지만 열의 출력은 어렵다.


#numpy를 활용한 1열 출력
data2d=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

arr = np.array(data2d)
print(arr[ : ,0])
#이 경우 arr[행:열] 혹은 arr[행][열]로 특정 원소에 접근
#가능하고
#arr[:,0]->전체 행에 대해서 0번째 열(1열)을 출력=0번째 열(1열) 출력
#arr[0, :]->처음 행에 대해서 모든 열을 출력=0번째 행(1행) 출력

'''
numpy를 활용해서 array를 만들면 리스트보다 쉽게
특정 위치의 원소나 행, 열의 선택이 쉽고 개별 원소의 
연산이 간단하다.
'''

[10, 20, 30]
[10 20 30]
[1, 2, 3]
[1 4 7]
