In [17]:
import numpy as np
#numpy의 인덱싱과 슬라이싱
#1차원 ndarrary의 인덱싱: arr[n] -> n번째 데이터 선택
#2차원 ndarrary의 인덱싱: arr[n][p] -> n행 p열의 데이터 선택
arr = np.arange(4)
print(arr)
print(arr[0])

arr = np.arange(4).reshape(2,2)
print(arr)
print(arr[0][0])


#ex) arange로 0~3범위 데이터로 만들어진 ndarray를 만들고
#reshape하여 2x2로 변환하라
a = np.arange(4).reshape(2,2)
print('답은 \n',arr)

[0 1 2 3]
0
[[0 1]
 [2 3]]
0
답은 
 [[0 1]
 [2 3]]


In [25]:
#timeit 명령: 주피터 노트북의 명령어
#해당 명령어 뒤의 코드를 1000만번 반복 후 걸린 시간의 평균 반환
a = np.arange(10000).reshape(100,100)
%timeit a[0,50]
%timeit a[0][50]

#이 경우 a의 0번째 행의 51번째 열의 데이터를 10000만번 
#반복 출력 이후 그것의 평균 시간을 출력한다. 
#2차원의 ndarray의 경우 해당 위치를 각각 인덱싱하는 것 보다
# 한번에 인덱싱(리스트 형태로)이 처리 속도가 더 빠르다.

154 ns ± 5.67 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
309 ns ± 16.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [33]:
#복수의 데이터를 가져오는 슬라이싱
#1차원 ndarray 데이터의 슬라이싱: arr[n:p] -> n번째부터 p-1번째 데이터 출력
#2차원 ndarrary 데이터의 슬라이싱: arr[a1:a2,b1:b2]->a1번째~a2-1번째 행,b1번째~b2-1번째 열의 데이터 출력
#2차원 ndarrary 데이터의 행 출력: arr[n:p]
#2차원 ndarrary 데이터의 열 출력: arr[:][n:p] , arr[:,n:p]

arr = np.arange(4)
print(arr)
print(arr[:2])

arr=np.arange(20).reshape(4,5)
print(arr)
print(arr[:2,:3])

#ex)리스트와의 차이점:
#4X5의 행렬에서 2개의 행 출력
# ndarray의 경우
arr = np.arange(20).reshape(4,5)
print(arr[:2])

#list의 경우
result = []
for row in arr : 
    row01 = [row[0],row[1]]
    result.append(row01)
print(result)

#행열 정보의 인덱싱 및 슬라이싱의 경우 
#list형태 보다는 np.arange를 통한 ndarrary형태가 유용하다.


[0 1 2 3]
[0 1]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0 1 2]
 [5 6 7]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0, 1], [5, 6], [10, 11], [15, 16]]
