In [18]:
import numpy as np
#numpy 내장 함수
#.sum(): 해당 ndarray 내의 원소의 총 합
arr = np.arange(1,11).reshape(2,5)
print(arr)
arr.sum()
#.sum()에 축(axis=n) 정보를 지정해 계산이 가능하다.
#axis=0:개별 열들의 데이터의 합
#axis=1:개별 행들의 데이터의 합
print(arr.sum(axis=0))
print(arr.sum(axis=1).reshape(2,1))

#sum()(총합)뿐 아니라, min,max,mean,std(표준편차),
#var(분산)도 활용이 가능하다

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 7  9 11 13 15]
[[15]
 [40]]


In [38]:
#numpy를 활용한 임의의 숫자 생성
#np.random.randint(n,size=(p,q)): 
# 0에서 n까지의 정수에 대해서 pxq의 ndarray 행렬을 반환한다.
#이때, size를 생략하면 ndarray가 아닌 정수 1개가 반환된다.
print(np.random.randint(3))
print(np.random.randint(45,size=(2,2)))

1
[[10 22]
 [32 16]]


In [44]:
#linspace함수
#np.linspace(n,p,q):
# n에서 p까지 q개로 분할해서 ndarray 형태로 반환한다.
x = np.linspace(0,100,11)
print(x)
#이때, q개의 지점에 시작값(n), 종료값(p)가 포함된다.

#만일 반환된 값에 대한 함수를 만들고 싶다면 다음과 같이 
#만들 수 있다.
y = x**2
print(y)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[    0.   100.   400.   900.  1600.  2500.  3600.  4900.  6400.  8100.
 10000.]


In [53]:
#stack함수 ->이때 묶는 대상은 list나 튜플처럼 묶여있어야 한다.
a = np.arange(4)
b = np.arange(4,8)

#np.vstack([a,b]):(v의미=verticalilty:수직)
#ndarray데이터 a,b를 수직으로 바인딩한다.
c = np.vstack((a,b))
print(c)

#np.hstack([a,b]):(h의미=horizontality(수평))
#ndarray데이터 a,b를 수평으로 바인딩한다.
d=np.hstack([a,b])
print(d)

[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]
