In [2]:
# Numpy(넘파이) : 선형 대수 계산에 주로 사용되는 라이브러리,
#                 속도, 편의성에서 우수하다.

#넘파이(Numpy) - array() 예시
# 리스트, 튜플, 배열에서 행렬을 생성한다.
import numpy as np

np_array_1 = np.array([1,2,3,4,5])
print(np_array_1)

np_array_2 = np.array([[1,2,3], [4,5,6]])
print(np_array_2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [3]:
#np.array()로 만든 데이터 타입은 ndarray로 나타난다.
#np.array()를 사용하면 축의 개수(ndim), 크기(shape)를 출력할 수 있다.
print('array_1의 축의 개수 : ', np_array_1.ndim)
print('array_1의 크기 : ', np_array_1.shape)

print(np_array_2.ndim)
print(np_array_2.shape)



array_1의 축의 개수 :  1
array_1의 크기 :  (5,)
2
(2, 3)


In [4]:
#zeros() : 영행렬을 생성한다.
zero_array = np.zeros((3,3))

print(zero_array)

#ones() : 모든 원소가 1인 행렬을 생성한다.
one_array = np.ones((2,3))

print(one_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
#full() : 모든 원소의 값을 지정 값으로 만든 행렬을 생성한다.
full_array = np.full((3,4),5)

print(full_array)

#eye() : 단위행렬을 생성한다.
eye_array = np.eye(3)

print(eye_array)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
#random.random() : 0과 1 사이의 임의 값을 원소로 하는 배열 생성
random_array = np.random.random((2,2))

print(random_array)

[[0.41643512 0.11592573]
 [0.42822499 0.39227732]]


In [7]:
#arrange() : 0부터 n-1까지의 원소값을 가지는 배열 생성
arange_array = np.arange(10)

print(arange_array)

#arrange(i,j,k) : i부터 j-1까지 k씩 증가하는 배열 생성
arange_array_2 = np.arange(1,20,2)

print(arange_array_2)

#reshape() : 배열의 데이터 변경 없이 구조만 바꾼다.
arange_array_3 = np.arange(30)
reshape_array = arange_array_3.reshape((5,6))

print(reshape_array)

[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [8]:
#참고용
# 넘파이 요소 간 연산
#덧셈: np.add()
#뻴셈 : np.subtract()
#곱셈 : np.multiply()
#나눗셈 : np.divide()
'''
행렬곱은 @를 사용해야만 한다.
행렬의 내적은 .dot()을 사용한다.
'''

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

result = np.dot(x,y)
result2 = x@y

print(result)
print(result2)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
